plugins {
	id 'java-library'
}

dependencies {
	api project(':module:web')
	api libs.spring.boot.starter.security

	implementation libs.spring.boot
	implementation libs.spring.boot.autoconfigure
	implementation libs.spring.context
	implementation libs.jackson.databind
	implementation libs.jackson.datatype.jsr310
	implementation libs.slf4j.api
	compileOnly libs.lombok
	annotationProcessor libs.lombok

	testImplementation libs.spring.boot.starter.test
	testImplementation libs.spring.security.test
	testRuntimeOnly libs.junit.platform.launcher
}
