[versions]
dependency-management = "1.1.7"
findsecbugs = "1.14.0"
spring-boot = "3.5.14"
spotbugs-gradle = "6.1.2"
spotbugs-tool = "4.9.3"
spotless = "8.1.0"

[libraries]
findsecbugs-plugin = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
lombok = { module = "org.projectlombok:lombok" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }

[plugins]
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-gradle" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
